L13 authorization
Lokideos/qna pull request #12
Opened 2018-04-05 12:53 UTC by Lokideos

В рамках данного пул реквеста был реализован следующий функционал:

Был создан и протестирован механизм авторизации с помощью гема CanCanCan для контроллеров Answer, Question и Comment.
Так как аутентификация должна происходить до авторизации, то для контроллеров девайса и связанных с ним авторизация была пропущена (в initializers).

2018-04-05 16:10 UTC, vkurennov requested changes

2018-04-05 16:10 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
Сделай обработку ошибки авторизации для всех типов запросов (html, js, json). для js и json можно возвращать 403 статус (forbidden), на клиенте его перехватывать и выводить сообщение

2018-04-05 16:10 UTC, vkurennov commented on app/models/ability.rb
> +    can :update, [Question, Answer, Comment], user: user
Проверку лучше делать по user_id, чтобы не грузить лишнюю ассоциацию

2018-04-05 16:10 UTC, vkurennov commented on app/models/ability.rb
> +      answer.question.user == user
Для этого у тебя есть метод `User#author_of?`

2018-04-05 16:15 UTC, vkurennov requested changes

2018-04-05 16:15 UTC, vkurennov commented on spec/models/ability_spec.rb
> +    it { should_not be_able_to :choose_best, create(:answer, question: question, user: author), user: author }
Тут не достаточно передавать user последним параметром, важно, чтобы автором был тот юзер, который создается через `let(:user)`

2018-04-05 16:15 UTC, vkurennov commented on spec/models/ability_spec.rb
> +    it { should_not be_able_to :choose_best, create(:answer, question: question, user: author), user: other }
Здесь то же самое

2018-04-08 14:46 UTC, Lokideos commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
Я поправил, но комментарий остался еще т_т

2018-04-09 08:05 UTC, vkurennov requested changes

2018-04-09 08:05 UTC, vkurennov commented on app/models/ability.rb
> +    item.ratings.each do |rating|
Это не верно. Зачем перебирать все голоса? Надо найти один голос от этого юзера (через where) и если он есть, значит, юзер имеет право на удаление. Если нет - не имеет.

2018-04-09 08:05 UTC, vkurennov commented on spec/models/ability_spec.rb
> +    it { should_not be_able_to :cancel_rate, question_rating.ratable, user: other }
Указание третьего параметра не влияет, на самом деле, на то, какой юзер будет использоваться в тесте. На это влияет только то, с каким юзером был создан Ability, у тебя используется для этого фабрика user. То есть у тебя голос создан от этого же пользователя, поэтому он и может его удалить. Нужно создать голос  от имени юзера other и тут его использовать, тогда и тесты пройдут.

2018-04-11 08:54 UTC, vkurennov approved these changes

2018-04-11 08:54 UTC, vkurennov commented on app/controllers/application_controller.rb
> +      format.js { render json: exception.message, status: :forbidden }
Так сделай тут также как в json, тогда упростистся обработка на уровне клиента. Какой смысл ошибки по-разному возвращать, если в обоих случаях все равно приходит json?

2018-04-11 08:54 UTC, vkurennov commented on app/models/ability.rb
> +    item.ratings.where(user_id: user.id) && !user.author_of?(item)
Тогда стоит использовать метод `can_rate?` для второй части условия, чтобы не дублировать код

2018-04-16 17:44 UTC, merged