L15 rest api 2
Lokideos/qna pull request #14
Opened 2018-04-19 17:42 UTC by Lokideos

В рамках данного пул реквеста был реализован следующий функционал:

Был создан и протестирован механизм просмотра отдельных вопросов и ответов и их списка через запросы к API;
На данный момент реализуется функционал, позволяющий через API создавать вопросы и ответы.

2018-04-20 05:53 UTC, vkurennov requested changes

2018-04-20 05:53 UTC, vkurennov commented on config/routes.rb
> +        get :index, on: :collection
Зачем  index-то как кастомный экшн указывать? Он же стандартный, ты же в других ресурсах его не пишешь

2018-04-20 05:53 UTC, vkurennov commented on config/routes.rb
> +        get :show_answers, on: :member
Это лишнее, чтобы получить ответы, нужно сделать запрос к questions/:id/answers, отдельный экшн для этого не нужен

2018-04-20 05:53 UTC, vkurennov commented on spec/api/v1/questions_spec.rb
> +        expect(response).to be_success
Чтобы понять в чем проблема, надо посмотреть, какой именно статус здесь вовзвращается - 401 или 403, если 401,  значит, доркипер не аутентифицирует пользоваетля, если 403 - значит дело в CanCan. Поняв, что именно происходит, можно уже дальше разбираться почему происходит.

2018-04-20 08:48 UTC, Lokideos commented on config/routes.rb
> +        get :index, on: :collection
Принято :)

2018-04-20 08:48 UTC, Lokideos commented on config/routes.rb
> +        get :show_answers, on: :member
Ой точно Т_Т В следующий раз внимательнее писать буду.

2018-04-20 08:50 UTC, Lokideos commented on spec/api/v1/questions_spec.rb
> +        expect(response).to be_success
А где можно найти, примеры для отправки POST запроса через REST-client? А то я хотел потестить, но не вышло :(

2018-04-30 10:18 UTC, vkurennov approved these changes

2018-05-02 08:53 UTC, merged