Auth answers acceptance
Lokideos/qna pull request #3
Opened 2017-07-29 01:38 UTC by Lokideos

2017-07-29 11:29 UTC, vkurennov requested changes

2017-07-29 11:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def index
Зачем нам index для ответов, если список на странице вопроса?  То же самое для show и new - и сам ответ и форма нового ответа должны быть на странице вопроса

2017-07-29 11:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def index
При create, если овтет не валидный надо делать рендер страницы вопроса, раз форма там.

2017-07-29 11:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def destroy
Где проверка на автора? Интерфейс легко обойти и послать запрос на прямую.

2017-07-29 11:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def set_question_for_del_and_edit
Почему не просто set_question? Какая разница для чего? Давай более краткие и емкие имена методам, не углубляйся в детали.

2017-07-29 11:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :question_id, :user_id)
Ни question_id ни user_id не передаются в параметрах запроса. Первый передается в url (но не внутри answer), а второй мы берем сразу в контроллере через current_user и передавать ничего не нужно.

2017-07-29 11:29 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user_id)
user_id не передается в форме, а в create  воспрос должен связываться с current_user

2017-07-29 11:29 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :question_id, :user_id)
Ну и в create  у тебя не связывается ответ с current_user

2017-07-29 11:29 UTC, vkurennov commented on app/controllers/questions_controller.rb
>  class QuestionsController < ApplicationController
Где проверка на автора при удалении?

2017-07-29 11:29 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      - if current_user.id == answer.user_id
Такая проверка будет нужна часто, в том числе в контроллере, поэтому стоит ее вынести в метод `User#author_of?` и вызывать в нужных местах.

2017-07-29 11:29 UTC, vkurennov commented on app/views/answers/_form.html.slim
> +    = f.label :user_id, hidden: true
Зачем label для скрытого поля?

2017-07-29 11:29 UTC, vkurennov commented on app/views/answers/_form.html.slim
> +    = f.text_area :user_id, value: current_user.id, hidden: true
1. Почему  text_area?
2. Здесь дыра в безопасности, я легко могу подставить любой id в скрытое поле и создать ответ от другого юзера
3. Связывать с current_user надо в контроллере, т.к. там будет именно текущий залогиненный юзер и изменить это извне нельзя

2017-07-29 11:29 UTC, vkurennov commented on app/views/questions/_form.html.slim
> +  = f.text_field :user_id, value: current_user.id, hidden: true
Опять же дыра, связявать надо в контроллере

2017-07-29 11:29 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +    - if current_user.id == question.user_id
Замени на вызов `User#author_of?`

2017-07-29 11:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- unless current_user == nil
Не срвнивай с nil, лушч просто `if current_user`, это то же самое

2017-07-29 11:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- else
Не используй else с unless, меняй на if

2017-07-29 11:29 UTC, vkurennov commented on app/views/questions/show.html.slim
>      = render @question.answers
Справишивается, зачем тебе answers/show?

2017-07-29 11:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render 'answers/form', question: @question, answer: @answer
И зачем нужен экшн answers/new?

2017-07-29 11:29 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if current_user.id == @question.user_id
Замени на вызов `User#author_of?`

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/create_answer_to_question_spec.rb
> +    create_question
Данные, необходимые для теста лучше создавать через фабрики и given/let

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/create_answer_to_question_spec.rb
> +    click_on 'Sign Out'
Зачем логинить, а потом выходить, когда можно сразу не логинить юзера?

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/create_answer_to_question_spec.rb
> +    expect(page).to have_content 'You have to log in to the system to be able to create answers.'
Т.е. просто посмотреть вопросы и его ответы гость не может? Странное решение

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/create_answer_to_question_spec.rb
> +feature 'Create answer to question', %q{
Нужен сценарий с ошибками валидации, проверить, что система сообщает пользователю об этих ошибках

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Нужно проверить наличие текста вопроса на странице (и заголовок тоже)

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Нужен сценарий с невалидным вопросом

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/delete_q_n_a_by_author_spec.rb
> +feature 'Delete questions and answers only by author', %q{
Это 2 разные фичи - уаление вопроса и удаление ответа, нужно разделить тесты на 2 файла

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/delete_q_n_a_by_author_spec.rb
> +    create_question
Создавай через фабрики и given

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/delete_q_n_a_by_author_spec.rb
> +    expect(page).to_not have_content "My Test Question"
Стоит убедиться, что этот контент был до удаления на странице

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/delete_q_n_a_by_author_spec.rb
> +    expect(page).to_not have_content "My Test Answer"
Стоит убедиться, что этот контент был до удаления на странице

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/delete_q_n_a_by_author_spec.rb
> +    click_on "Sign Out"
А не проще сразу создать вопрос/ответ и делать все от незалогиненного юзера, без его логина и выхода?

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/inspect_questions_list_spec.rb
> +    expect(page).to have_content "Questions List"
Это один ответ, а не список вопросов. Надо проверить, что отображается именно список, причем разных вопросов (используй sequence в фабриках для этого)

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/inspect_questions_list_spec.rb
> +    expect(page).to have_content "My Test Question"
И опять же это один вопрос, а не список

2017-07-29 11:29 UTC, vkurennov commented on spec/acceptance/inspect_questions_list_spec.rb
> +feature 'Inspect question list', %q{
Где аналогичный тест для **списка** ответов?

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'GET #index' do
Нам не нужен это экшн и тесты для него

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'GET #show' do
Нам не нужен это экшн и тесты для него

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'GET #new' do
Нам не нужен это экшн и тесты для него

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    before { get :edit, params: { user_id: user.id, question_id: question.id, id: answer } }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { user_id: user.id, question_id: question.id, answer: attributes_for(:answer) } }.to change(Answer, :count).by(1)
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { user_id: user.id, question_id: question.id, answer: attributes_for(:answer) }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'saves the new answer and its association to correct question' do
Нужен похожий тест на проверку связи с залогиненным юзером

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { user_id: user.id, question_id: question.id, answer: attributes_for(:answer) }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { user_id: user.id, question_id: question.id, answer: attributes_for(:invalid_answer) } }.to_not change(Answer, :count)
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        post :create, params: { user_id: user.id, question_id: question.id, answer: attributes_for(:invalid_answer) }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        patch :update, params: { user_id: user.id, question_id: question.id, id: answer, answer: attributes_for(:answer) }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        patch :update, params: { user_id: user.id, question_id: question.id, id: answer, answer: { body: 'new body' } }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        patch :update, params: { user_id: user.id, question_id: question.id, id: answer, answer: attributes_for(:answer) }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      before { patch :update, params: { user_id: user.id, question_id: question.id, id: answer, answer: { body: nil } } }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      it 'deletes answer' do
Тут должно быть 2 контекста: для автора и для не-автора

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect { delete :destroy, params: { user_id: user.id, question_id: question.id, id: answer } }.to change(Answer, :count).by(-1)
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      delete :destroy, params: { user_id: user.id, question_id: question.id, id: answer }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    before { get :index, params: { user_id: user.id } }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    before { get :show, params:{ user_id: user.id, id: question } }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    before { get :new, params: { user_id: user.id } }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    before { get :edit, params: { user_id: user.id, id: question } }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { user_id: user.id, question: attributes_for(:question) } }.to change(Question, :count).by(1)
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { user_id: user.id, question: attributes_for(:question) } }.to change(Question, :count).by(1)
Тут нужно еще проверить связь с залогиненным юзером

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        post :create, params: { user_id: user.id, question: attributes_for(:question) }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { user_id: user.id, question: attributes_for(:invalid_question) } }.to_not change(Question, :count)
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        post :create, params: { user_id: user.id, question: attributes_for(:invalid_question) }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        patch :update, params: { user_id: user.id, id: question, question: attributes_for(:question) }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        patch :update, params: { user_id: user.id, id: question, question: { title: 'new title', body: 'new body' } }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        patch :update, params: { user_id: user.id, id: question, question: attributes_for(:question) }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        patch :update, params: { user_id: user.id, id: question, question: { title: 'new title', body: nil } }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        post :create, params: { user_id: user.id, question: attributes_for(:question) }
Создавай начальные данные через фабрики

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
Тут должно быть 2 контекста: для автора и для не-автора

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      expect { delete :destroy, params: { user_id: user.id, id: question } }.to change(Question, :count).by(-1)
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-07-29 11:29 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      delete :destroy, params: { user_id: user.id, id: question }
user_id не должен передаваться в параметрах, его надо брать сразу в контроллере

2017-08-01 12:25 UTC, Lokideos commented on spec/acceptance/create_answer_to_question_spec.rb
> +    click_on 'Sign Out'
Здесь я полностью эмулировал процесс создания вопроса, а т.к. вопрос создать нельзя без предварительного логина, то я решил залогиниться, хотя можно было обойтись и `User.create!`

2017-08-01 12:32 UTC, Lokideos commented on spec/acceptance/create_answer_to_question_spec.rb
> +    expect(page).to have_content 'You have to log in to the system to be able to create answers.'
Он же может. Просто не может ничего редактировать и удалять.

2017-08-02 07:03 UTC, iBublik requested changes

2017-08-02 07:03 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    @answer.user_id = current_user.id
Лучше не по id связывать, а так: `@answer.user = current_user`. В таком случае, если у нас вдруг поменяется поле для связи (например будет называться `author_id`), в коде ничего не придется менять

2017-08-02 07:03 UTC, iBublik commented on app/models/user.rb
> +  def self.author_of?(current_user, item)
Этот метод лучше сделать методом экземпляра. Тогда от передачи параметра пользователя можно избавиться и использовать так: `current_user.author_of?(question)`.

2017-08-02 07:03 UTC, iBublik commented on app/models/user.rb
> +    current_user == item.user
Вот тут лучше сравнивать по id, чтоб не грузить связь лишний раз (`id == item.user_id`)

2017-08-02 07:03 UTC, iBublik commented on app/views/answers/_answer.html.slim
> +      - if User.author_of?(current_user, answer)
Чтоб избежать двйной вложенности можно использовать оператор `&` - он позволяет обойтись без проверки на nil. Т.е. будет одно условие `if current_user&.author_of?(answer)`

2017-08-02 07:03 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  def error_msg(item)
У тебя есть партиал с выводом ошибок, зачем во флеше дублировать их? Можно просто вывести сообщение, что не удалось сохранить запись

2017-08-02 07:03 UTC, iBublik commented on app/views/questions/show.html.slim
> +- if current_user
Тут лучше использовать хелпер `user_signed_in?` - он делает то же самое, но семантически более понятно что ты проверяешь

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/create_answer_to_question_spec.rb
> +    question
Зачем это делать? В строке ниже ты переходишь на страницу вопроса, в этот момент он и создастся в базе

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/create_answer_to_question_spec.rb
> +    question
В других тестах аналогично это действие избыточно

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/delete_answer_by_author_spec.rb
> +  given(:user2){ create(:user) }
Давай более осмысленные названия, чтоб по ним была понятна суть - например, `author`, `non-author`

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/delete_answer_by_author_spec.rb
> +    answer
Чтоб на момент начала теста хелпер был выполнен, используй бэнг-версии - `let!/given!`. В данном случае это вызовет сохранение ответа в базу до начала теста, так что в теле теста можно сразу переходить на страницу вопроса, ответ будет к нему прикреплен

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/delete_answer_by_author_spec.rb
> +    expect(page).to have_content answer.body
То что на странице вопроса отображаются его ответы проверяется в другом тесте, тут это не надо проверять

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/delete_answer_by_author_spec.rb
> +    click_on "Delete"
У тебя и у вопроса ссылка на удаление так же называется. Либо для вопросов/ответов назови ссылки по-разному, либо явно сужай область поиска кнопки с помощью `within`:
```ruby
within(answer_selector) { click_on 'Delete' }
```

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/delete_question_by_author_spec.rb
> +feature 'Delete questions only by author', %q{
Тут замечания аналогичны тестам удаления ответа

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/inspect_answers_list_spec.rb
> +  given(:answer) { create(:answer, user: user, question: question) }
Зачем это?

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/inspect_answers_list_spec.rb
> +  given(:answers) { create_list(:answer, 3, user: user, question: question) }
Тут стоит использовать `given!`

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/inspect_answers_list_spec.rb
> +    expect(page).to have_content('MyText', count: 3)
А вдруг это у тебя один и тот же ответ несколько раз вывелся? Проверь наличие каждого ответа с помощью цикла

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/inspect_questions_list_spec.rb
> +  given(:question) { create(:question) }
Не используется

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/inspect_questions_list_spec.rb
> +  given(:questions) { create_list(:question, 3, user: user) }
`given!`

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/inspect_questions_list_spec.rb
> +    expect(page).to have_content('Test Question', count: 3)
Нужна проверка каждого вопроса в цикле

2017-08-02 07:03 UTC, iBublik commented on spec/acceptance/sign_out_spec.rb
> +  scenario "Registered user tries to sign out" do
Ну это избыточно в отдельный тест выносить, можно в предыдущем проверить. Авот то что у незалогиненного пользователя нет кнопки "Sign Out" проверить можно

2017-08-02 07:03 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +  let(:user2) { create(:user) }
Замечание по более понятным именам актуально везде :)

2017-08-02 07:03 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +    before { controller.stub(:current_user).and_return (user) }
Зачем это делать? Текущий залогиненный юзер у нас хранится в переменной `@user`

2017-08-02 07:03 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).user_id).to eq user.id
Не очень красивая проверка, лучше через ассоциации смотреть - `expect { ... }.to change(@user.answers, :count).by(1)`

2017-08-02 07:03 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
Делай лучше `render 'questions/show'`. Тогда и ошибки во флеш не придется пихать

2017-08-02 07:03 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
Тут тоже render

2017-08-02 07:03 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
И тут render

2017-08-02 07:03 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +        @correct_title = question.title
Зачем задавать переменные экземпляра, если они только в одном месте используются? Использую локальные переменные в самом тесте

2017-08-02 07:03 UTC, iBublik commented on spec/factories/answers.rb
> +  sequence :body do |n|
Такие последовательности лучше в теле самой фабрики объявлять. Глобально объявляются только последовательности, которые используются в нескольких фабриках, и их обычно в `sequences.rb` переносят. Т.е. тут сделай так:
```ruby
factory :answer do
  sequence(:body) { |n| "MyText#{n}" }
end
```

2017-08-02 07:03 UTC, iBublik commented on spec/factories/answers.rb
>    factory :invalid_answer, class: "Answer" do
Фабрики можно вкладывать друг в друга, это некое подобие наследования. Тогда не придется указывать класс создаваемого объекта:
```ruby
factory :answer do
  ...
  factory :invalid_answer do
    ...
  end
end
```

2017-08-02 07:03 UTC, iBublik commented on spec/factories/questions.rb
>  FactoryGirl.define do
См. мои рекомендации к фабрике ответов

2017-08-02 07:03 UTC, iBublik commented on spec/factories/questions.rb
> +  factory :question_without_user do
Зачем такая фабрика? У нас в системе нет анонимных вопросов

2017-08-02 07:03 UTC, iBublik commented on spec/factories/questions.rb
> +    user
Зачем в заведомо невалидной фабрике создавать юзера?

2017-08-02 07:03 UTC, iBublik commented on spec/models/user_spec.rb
> +RSpec.describe User do
Нужны тесты на метод `author_of?`

2017-08-02 08:13 UTC, Lokideos commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
Я пробовал, но у меня тогда если создавать ответ с неправильными параметрами выскакивает ошибка ActionController:UrlGenerationError in` Answers#create` `No route matches {:action=>"edit", :controller=>"answers", :id=>nil, :question_id=>"23}, missing required keys: [:id]`
Собственно, покопавшись на stackoverflow как раз и нашел такой вариант с редиректом и отображением ошибок через flash.

2017-08-02 08:14 UTC, Lokideos commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
Такая же история, как и с прошлым рендером.

2017-08-02 08:14 UTC, Lokideos commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
То же самое.

2017-08-02 08:15 UTC, Lokideos commented on app/controllers/answers_controller.rb
> +  def error_msg(item)
Просто так как я делаю редирект, партиал не срабатывает.

2017-08-02 08:21 UTC, Lokideos commented on app/views/questions/show.html.slim
> +- if current_user
В общем, я оставил оба варианта: один с `if current_user&.author_of?` и один с` user_signed_in?` и вложенным if'ом

2017-08-02 08:26 UTC, Lokideos commented on spec/acceptance/create_answer_to_question_spec.rb
> +    question
Что-то я как-то упустил это. То есть объявляя `given`, мы не хелпер создаем, а создаем все, что перечислено в нем перед каждым сценарием?

2017-08-02 08:28 UTC, Lokideos commented on spec/acceptance/delete_answer_by_author_spec.rb
> +    answer
Хм. А есть какие-то рекомендации, когда использовать и когда не использовать бэнг-версии данных методов?

2017-08-02 08:39 UTC, iBublik commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
Получился костыль :) Тебе надо в списке ответов к вопросу рендерить только сохраненные ответы (`persisted?`), тогда ошибки этой не будет

2017-08-02 08:42 UTC, iBublik commented on spec/acceptance/create_answer_to_question_spec.rb
> +    question
Нет, `let/given` как раз хелпер создает. Код из него выполняется при первом вызове и результат запоминается, в дальнейшем он будет использоваться.
Когда ты пишешь `visit question_path(question)` вызывается хелпер `question`, и ответ создается в базе

2017-08-02 08:44 UTC, iBublik commented on spec/acceptance/delete_answer_by_author_spec.rb
> +    answer
Ну когда на начало теста тебе ну жно чтоб хелпер был выполнен - используй бэнг версию.
Например, ты просматриваешь список вопросов. Переходишь на страницу `visit questions_path` - она будет пустой, т.к. хелпер еще не вызван, вопросы в базе не созданы. А если сделать `given!(:questions) { create_pair :question }` - то начало теста вхелпер уже выполниться, и в списке отрендерятся созданные вопросы.

2017-08-02 08:48 UTC, Lokideos commented on spec/acceptance/delete_answer_by_author_spec.rb
> +    click_on "Delete"
Я так понимаю, для within придется css селекторы добавлять, так что я пока что в локалях переименую кнопки. Но в целом как лучше делать - разные названия кнопкам давать или заключать кнопки (ссылки) в `div `и назначать нужный селектор?

2017-08-02 11:33 UTC, vkurennov requested changes

2017-08-02 11:33 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
Да, нужен render, а не редирект

2017-08-02 11:33 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
И то же решение

2017-08-02 11:33 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if current_user
Зачем 2 варианта? Выбери один и его и используй

2017-08-02 11:47 UTC, Lokideos commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question)
Внезапно я справился.

2017-08-02 18:54 UTC, merged