Ajax 2 answers additional functionality
Lokideos/qna pull request #5
Opened 2017-08-10 13:14 UTC by Lokideos

2017-08-10 14:01 UTC, vkurennov requested changes

2017-08-10 14:01 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +$(document).on('turbolinks:update',ready);
Это лишнее, только на turbolinks:load достаточно вешать обработчик

2017-08-10 14:01 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +  $('.edit-answer-link').click(function(e) {
Не отрабатывает, скорее всего потому что click вешает обработчики только на уже существующие элементы. Если ответ создан динамически, через ajax, то на него обработчик не будет повешен.  Решение: заменить `$('.edit-answer-link').click(function(e)` на 

`$(document).on('click', '.edit-answer-link', -> (e)`.

2017-08-10 14:01 UTC, vkurennov commented on app/models/answer.rb
> +    question.answers.each do |answer|
Используй update_all

2017-08-10 14:01 UTC, vkurennov commented on app/models/answer.rb
> +    answer.update(best_answer: true)
Т.к. изменений несколько, да еще и у разных объектов, то нужно использовать [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными.

2017-08-10 14:01 UTC, vkurennov commented on app/models/answer.rb
> +  def only_one_answer_can_be_best
Что за жуткий подсчет, да еще и перебором. Достаточно поставить валидацию на уникальность или использовать метод `exists?` с аргументами.

2017-08-10 14:01 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +  $('.answer-' + '<%= @answer.id %>').html('');
Используй remove для удаления элемента со страницы

2017-08-10 14:01 UTC, vkurennov commented on spec/acceptance/choose_best_answer.rb
> +    within '.best-answer' do
Тут надо убедиться, что там нет контента 3-го ответа, а то может они оба добавились?

2017-08-10 14:01 UTC, vkurennov commented on spec/models/answer_spec.rb
>  RSpec.describe Answer, type: :model do
А где же тесты на метод choose_best?

2017-08-10 14:01 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  context "Validations" do
И где тесты на твою валидацию уникальности лучшего ответа?

2017-08-11 08:15 UTC, vkurennov requested changes

2017-08-11 08:15 UTC, vkurennov commented on app/models/answer.rb
> +        old_answer.update(best_answer: false)
Транзакция откатывается только в случае исключения, поэтому тут должен быть `update!`

2017-08-11 08:15 UTC, vkurennov commented on app/models/answer.rb
> +      answer.update(best_answer: true)
Тут тоже должен быть `update!`

2017-08-11 08:15 UTC, vkurennov commented on app/models/answer.rb
> +    if self.question.answers.where(best_answer: true).length > 1
А нужна ли вообще тебе эта валидация? Ведь у тебя метод и так работает таким образом, чтобы сбрасывать старый лучший ответ.

2017-08-11 08:15 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  context 'methods test' do
принято делать describe на каждый метод, т.е. тут должно быть:

`describe "#choose_best_answer"`, а внутри уже все тесты для этого метода

2017-08-11 08:15 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.choose_best_answer(answer)).to eq true
Вот тут ты проверяешь то ,что вернет тебе метод `choose_best_answer`, а не то, что у ответа изменился флаг

2017-08-11 08:15 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.choose_best_answer(answer2)).to eq true
И опять же это проверка того, что вернет метод. а надо проверить, что старый ответ стал не лучшим, а новый - лучшим

2017-08-11 14:36 UTC, Lokideos commented on app/models/answer.rb
> +    if self.question.answers.where(best_answer: true).length > 1
Я просто помню, когда мы проходили валидации, была рекомендация ставить валидации даже если на данный момент нет функционала, который мог бы привести к появлению неверных значений, т.к. в дальнейшем такой функционал может появиться.

2017-08-11 14:37 UTC, Lokideos commented on spec/models/answer_spec.rb
> +  context 'methods test' do
Т.е. мне под контекстом добавить `describe `на данный метод?

2017-08-11 14:40 UTC, Lokideos commented on spec/models/answer_spec.rb
> +      expect(answer.choose_best_answer(answer2)).to eq true
Я к сожалению только завтра вечером доберусь до VM с моим проектом. Я правильно понимаю, что мне надо добавить после создания ответов добавить 2 строчки?`answer.choose_best_answer(2)`
`expect(answer2.best_answer).to eq true`

2017-08-13 10:24 UTC, vkurennov approved these changes

2017-08-14 14:33 UTC, merged