Rate qna ajax concerns
Lokideos/qna pull request #7
Opened 2017-08-23 03:31 UTC by Lokideos

2017-08-23 08:13 UTC, vkurennov requested changes

2017-08-23 08:13 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +    var rating = $.parseJSON(xhr.responseText);
Здесь же полное дублирование с предыдущим обработчиком. Повесь один обработчик на разные классы:

`$('a.rate-good-answer, a.rate-bad-answer').bind(...)`

2017-08-23 08:13 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +    var rating = $.parseJSON(xhr.responseText);
И тут еще дублирование

2017-08-23 08:13 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +    var rating = $.parseJSON(xhr.responseText);
Или даже лучше: сделай им не разные, а одинаковый класс, тогда у тебя будет один универсальный обработчик на все подобные ссылки, даже если действия у ссылок будут разными

2017-08-23 08:13 UTC, vkurennov commented on app/assets/javascripts/questions.js
> +  $('a.rate-good-question').bind('ajax:success', function (e, data, status, xhr) {
Те же замечания, что и к обработчикам для ответов. Тут вообще можно сделать один обработчик и для вопросов и для ответов, а определять `question` это или `answer` (и составлять соответсвующие селекторы) можно используя поле `commentable_type` из пришедшего json

2017-08-23 08:13 UTC, vkurennov commented on app/controllers/concerns/rated.rb
> +      rate_responde(@item)
Зачем передавать **инстанс-переменную** как параметр? она же и так доступна в любом методе внутри этого класса.

2017-08-23 08:13 UTC, vkurennov commented on app/controllers/concerns/rated.rb
> +    if current_user.not_author_of?(@item)
Здесь как раз наоборот - удалять голос может только тот, кто его создал, т.е. автор **голоса**. Иначе получается, что я могу удалять твои голоса, а ты мои.

2017-08-23 08:13 UTC, vkurennov commented on app/models/concerns/ratable.rb
> +    def rating?(user)
Метод возращает объект, а не true/false, т.е. это не предикат и его нельзя называть с вопр. знаком в конце. Этим ты вводишь в заблуждение

2017-08-25 08:01 UTC, Lokideos commented on app/assets/javascripts/answers.js
> +    var rating = $.parseJSON(xhr.responseText);
У меня там немного другой функционал заложен в этот обработчик, поэтому не получается от него избавиться.

2017-08-25 08:17 UTC, Lokideos commented on app/controllers/concerns/rated.rb
> +    if current_user.not_author_of?(@item)
Чего-то я не то написал :))

2017-08-25 08:23 UTC, Lokideos commented on app/controllers/concerns/rated.rb
> +    if current_user.not_author_of?(@item)
@vkurennov Так все же в порядке. `@item` - это вопрос или ответ, а не рейтинг. Далее он смотрит в самом методе, есть ли строчка в таблице `ratings`, у которой `user` - это `current_user`, и если есть, то его удаляет. Если же нет, то ничего не происходит.

2017-08-25 10:56 UTC, vkurennov requested changes

2017-08-25 10:56 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +    var rating = $.parseJSON(xhr.responseText);
Ок, хотя бы от перового дублирования избавились.

2017-08-25 10:56 UTC, vkurennov commented on app/controllers/concerns/rated.rb
> +    if current_user.not_author_of?(@item)
Но тут получается сложная логика, она совершенно не очевидна из кода. Если юзер - не автор вопроса/ответа, это еще не значит, что юзер - автор голоса. Поэтому код должен явно проверять, что если юзер - автор голоса, то тогда удаляем голос. Код должен быть понятным и очевидным. Здесь явно код "с душком".

2017-08-25 10:56 UTC, vkurennov commented on app/models/user.rb
> +    id != item.user_id
Лучше используй тот же метод author_of? но с отрицанием, иначе, если вдруг проверка усложнится, придется переписывать оба, а так - только один метод

2017-08-25 10:56 UTC, vkurennov commented on spec/controllers/concerns/rated_controller_spec.rb
> +      patch :rate_good, params: { id: rating, format: :js }
У тебя rate_good/rate_bad  - это методы контрлллеров вопроса/ответа, вот и передавать нужно id вопроса/ответа. А чтобы проверять update рейтинга, нужно создать голос от залогиненного юзера за этот вопрос/ответ

2017-08-25 10:56 UTC, vkurennov commented on spec/controllers/concerns/rated_controller_spec.rb
> +  describe 'PATCH #rate_good' do
А где проверка создания нового голоса? У тебя же 2 варинта: юзер уже голосовал и мы меняем ему значение голоса и юзер еще не голосовал, мы создаем ему новый голос.

2017-08-25 10:56 UTC, vkurennov commented on spec/controllers/concerns/rated_controller_spec.rb
> +  it_behaves_like "Rated"
Это пишется в основной спеке.

2017-08-25 10:56 UTC, vkurennov commented on spec/controllers/concerns/rated_controller_spec.rb
> +
файл с shared-спекой не должен содержать _spec в названии, т.е. он не должен запускаться. Просто подгружаешь его в нужной спеке и вызываешь через  `it_behaves_like`

2017-08-25 10:56 UTC, vkurennov commented on spec/factories/ratings.rb
> +    factory :bad_rating do
Почему у тебя одна фабрика внутри другой? Для этого вообще-то traits используются.

2017-08-25 10:56 UTC, vkurennov commented on spec/models/concerns/ratable_spec.rb
> +  it "#add_rating" do
Тут, кстати, маловато тестов. Ты просто проверяешь возвращаемое значение, но ты же можешь из метода всегда 1 возвращать и тест пройдет. Надо проверить то, что создается объект рейтинга с нужным значением от нужного юзера, и то, что если уже есть такой рейтинг, то у него меняется значение.

2017-08-25 10:56 UTC, vkurennov commented on spec/models/concerns/ratable_spec.rb
> +    expect(WithRatable.create!.decrease_rating(user).value).to eq -1
Те же замечания, что и к  add_rating

2017-08-25 10:56 UTC, vkurennov commented on spec/models/concerns/ratable_spec.rb
> +    expect(WithRatable.create!.nullify_rating(user)).to eq nil
Вот это тоже ничего не проверяет. Напиши пустой метод nullify_rating в консерне и он будет возвращать nil, тест пройдет. Тестируй все, что должен делать метод, а не только то, что он возвращает. И всегда ли метод возвращает nil?

2017-08-25 10:56 UTC, vkurennov commented on app/models/user.rb
> +  def not_author_of?(item)
Где тесты на этот метод?

2017-08-27 09:59 UTC, vkurennov approved these changes

2017-08-27 09:59 UTC, vkurennov commented on spec/controllers/concerns/rated_controller.rb
> +shared_examples "Rated" do
Сделай проще пока: продублируй отдельно тесты для этих экшенов в тестах контроллеров вопросов и ответов. А когда пройдем shared-спеки, вынесешь это отдельно.

2017-08-30 09:53 UTC, merged